### ISSUE TITLE
[ERR_INVALID_URL]: Invalid URL: undefined v 1.4.0

### ISSUE THREAD

**Issue by DRTorrontegi** [ozantunca/elb-log-analyzer#298] opened 2020-09-18 15:19 UTC
internal/url.js:221
  throw error;
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Object.parseLine (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseLine.js:16:23)
    at Object.process (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/generateProcessor.js:39:56)
    at Interface.RL.on (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseAndProcessFiles.js:19:9)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at ReadStream.onend (readline.js:147:12)
    at emitNone (events.js:111:20)

**Comment by ozantunca** [comment] 2020-09-30 22:36
Hi @DRTorrontegi, thank you for posting this. Is it possible for you to send me that log file that causes the problem? I'm coding a fallback for the problem to keep the script from crashing. But I also want to get to the bottom of it.

**Comment by ozantunca** [comment] 2020-10-03 11:03
Duplicate of #251

**Closed by ozantunca** 2020-10-03 11:03 UTC
